[package]
name = "wikipedia-externallinks-fast-extraction"
version = "0.1.3"
authors = ["Ophir LOJKINE <o.lojkine@qwant.com>"]

[dependencies]
nom-sql = { git = "https://github.com/lovasoa/nom-sql" , branch="develop"}
